base           <https://example.org/>
prefix adms:   <http://www.w3.org/ns/adms#>
prefix dct:    <http://purl.org/dc/terms/>
prefix ebg:    <http://data.businessgraph.io/ontology#>
prefix locn:   <http://www.w3.org/ns/locn#>
prefix org:    <http://www.w3.org/ns/org#>
prefix schema: <http://schema.org/>
prefix skos:   <http://www.w3.org/2004/02/skos/core#>

