=encoding utf8

=head1 NAME

rdfpuml - Convert RDF to PlantUML diagrams

=head1 SYNOPSIS

  perl rdfpuml.pl file.ttl                         # makes file.puml
  java -jar plantuml.jar -charset UTF-8 file.puml  # makes file.png


=head1 DESCRIPTION

Converts an RDF Turtle file to a readable diagram using L<plantuml|http://plantuml.com>.

=head2 Motivation

The best way to understand RDF data schemas (ontologies, application profiles, RDF shapes) is with a diagram.
Many RDF visualization tools exist, but they have shortcomings, eg

=over

=item *

Focus on large graphs, where the details are not easily visible

=item *

Visualization results are not satisfactory

=item *

Manual tweaking of the diagrams is required

=back

B<rdfpuml> makes B<true> UML diagrams directly from Turtle examples,
with a small amount of tweaking that can be done with C<puml:> formatting triples
(this follows the approach from
L<Circles and arrows diagrams using stylesheet rules|https://www.w3.org/2001/02pd/>, Dan Connolly, W3C 2005).

Benefits:

=over

=item *

Guarantees consistency between what you say (triple statements) and what you show (diagram)

=item *

Lets you focus on domain modeling rather than diagram layouting/tweaking

=item *

Enables efficient source control

=item *

Saves you lots of effort

=back

=head2 Features

Diagram readability is a prime concern. B<rdfpuml> implements the following features for maximum readability.

=over


=item *

Shorten URLs aggressively. Some prefixed names you see in the diagram are not valid Turtle

=item *

Show B<inline> as much as possible: literal values, types, and nodes declared as C<puml:Inline>

=item *

Sort properties by name (rdf:type comes first)

=item *

Show literal datatypes, use Turtle shortcuts (eg 1 instead of "1"^^xsd:integer)

=item *

Collect property values together; collect "parallel" relations together

=item *

Show reified properties as UML Associations

=item *

Allow node decorations such as stereotypes, colored circles (and in the future: background color and icons)

=item *

Allow arrow decorations such as head, dashed, colored

=item *

Allow control of arrow directions

=item *

Allow hidden arrows to tweak the layout

=back

=head2 Prefixes

B<rdfpuml> prepends F<prefixes.ttl> if it finds such a fule, 
so when you make a set of examples, you can keep all your prefixes in one file.

It also predefines the following prefixes:

   puml   => 'http://plantuml.com/ontology#'
   rdf    => 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'
   rdfs   => 'http://www.w3.org/2000/01/rdf-schema#'
   skos   => 'http://www.w3.org/2004/02/skos/core#'
   crm    => 'http://www.cidoc-crm.org/cidoc-crm/'
   crmx   => 'http://purl.org/NET/cidoc-crm/ext#'
   frbroo => 'http://example.com/frbroo/'
   crmdig => 'http://www.ics.forth.gr/isl/CRMdig/'
   crmsci => 'http://www.ics.forth.gr/isl/crmsci/'
   leak   => 'http://data.ontotext.com/resource/leak/'

C<puml> is used for PlantUML formatting triples, see below.
C<rdfs> and C<skos> are used to display node labels.
The rest are used for reification (see below).

=head2 Parallel Arrows

Multiple property instances between nodes are collected in one arrow and shown as several labels.
Inverse arrows work fine.

=for html
<img src="img/CONA-arel-replaced-MultipleArrowLabels.png">

=for text
See F<img/CONA-arel-replaced-MultipleArrowLabels.png>

=head2 Reification

In RDF, B<Reification> is an approach where a statement B<s p o> is represented as a class instance
with 3 "addressing" properties and then additional properties are added to elaborate the statement
(eg probability, effective date range, who assigned the statement, etc).

This approach has been used in RDF for many years using the L<RDF Reification vocabulary|http://www.w3.org/TR/rdf-primer/#reification>.
It was developed for CIDOC CRM in the paper L<Types and Annotations for CIDOC CRM Properties|http://vladimiralexiev.github.io/pubs/Alexiev2012-CRM-Properties.pdf>
and is used for British Museum data (C<bmo:EX_Association, bmo:PX_property>),
see L<Reified Association|https://confluence.ontotext.com/display/ResearchSpace/BM+Association+Mapping+v2#BMAssociationMappingv2-TranslatedCodeInReifiedAssociation>.

B<rdfpuml> recognizes a number of reification "situations" and renders them as a L<UML Association|http://plantuml.com/classes.html#Association_classes>, for example

=for html
<img src="img/CONA-arel-Reification.png">

=for text
See F<img/CONA-arel-Reification.png>

RDF Reification looks like this:

  [] a rdf:Statement; rdf:subject s; rdf:predicate p; rdf:object o; <statement metadata>
  
C<rdf:Statement> is the reification class,
C<rdf:subject, rdf:predicate, rdf:object> are the addressing properties,
and it can be applied over any shortcut property B<p>.

The L<Property Reification Vocabulary|http://smiy.sourceforge.net/prv/spec/propertyreification.html> (PRV)
can be used to describe other reification situations, using terms like in the table below.
B<rdfpuml> recognizes the following situations, and in the future you should be able to provide your own PRV descriptions.

  REIFICATION CLASS             SUBJECT PROP                   SHORTCUT PROP                    OBJECT PROP                 SHORTCUT
  _____________________________ ______________________________ ________________________________ ___________________________ __________________________________________
  rdf:Statement                 rdf:subject                    rdf:predicate                    rdf:object                  <any>
  crm:E13_Attribute_Assignment  crm:P140_assigned_attribute_to crmx:property                    crm:P141_assigned           <any CRM prop>
  crm:E14_Condition_Assessment  crm:P34_concerned              crmx:property                    crm:P35_has_identified      crm:P44_has_condition
  crm:E15_Identifier_Assignment crm:P140_assigned_attribute_to crmx:property                    crm:P37_assigned            crm:P1_is_identified_by, crm:P102_has_title
  crm:E15_Identifier_Assignment crm:P140_assigned_attribute_to crmx:property                    crm:P38_deassigned          crm:P1_is_identified_by, crm:P102_has_title
  crm:E16_Measurement           crm:P39_measured               crmx:property                    crm:P40_observed_dimension  crm:P43_has_dimension
  crm:E17_Type_Assignment       crm:P41_classified             crmx:property                    crm:P42_assigned            crm:P2_has_type or subprop
  frbroo:F52_Name_Use_Activity  frbroo:R63_named               crmx:property                    frbroo:R64_used_name        crm:P1_is_identified_by, crm:P102_has_title
  crmsci:S4_Observation         crmsci:O8_observed             crmsci:O9_observed_property_type crmsci:O16_observed_value
  leak:Edge                     leak:hasSource                 <none>                           leak:hasTarget

For CIDOC CRM we need a new extension C<crmx:property> to point to the property being reified (the shortcut), similar to how C<rdf:predicate> is used.
Even for a specific CRM reification class like E17_Type_Assignment,
the shortcut property is not fixed to C<crm:P2_has_type>:
we may need to reify a sub-property thereof, e.g. C<crm:P72_has_language>.

Visuals: the shortcut is shown as a normal relation.
The reification node is attached to the relation usign a dashed line.
It is automatically positioned below or to the right of the relation, depending on the relation's direction.
The 3 "addressing" properties are shown inside the reification class,
and there are little characters in front of them to point to the
subject ("←" or "↑"), property (".." or ":") and object ("→" or "↓").

Limitation: you can show as reified a maximum of 2 relations between the same nodes, and even that is ugly.

=for html
<img src="img/CONA-titles-NoReify.png">

=for text
See F<img/CONA-titles-NoReify.png>

If you don't want to show a relation as reified (either because it's the third one between the same nodes or for other reasons,
use the C<puml:NoReify> class to tell B<rdfpuml> not to reify it, e.g.

  cona_term:1000000718-contrib-10000016 a puml:NoReify.

=for html
<img src="img/CONA-types-reification.png">

=for text
See F<img/CONA-types-reification.png>

=head2 Inlines

In order to save space, B<rdfpuml> inlines various resources in the subject node, rather than as a separate node.
All literals and types are inlined automatically.
In addition, you can inline other nodes by using the following.

=over

=item C<puml:Inline>

Shows a single node inline.
This is used quite often for lookup values, e.g.

  <cona/event/competition> a puml:Inline.
  cona_contrib:10000000 a puml:Inline; rdfs:label "Getty Vocabulary Program".

=item C<puml:InlineProperty>

Declares a property to be inlined, i.e. all its objects are shown inlined, e.g.

  fn:annotationSetFrame a puml:InlineProperty.
  fn:annotationSetLU    a puml:InlineProperty.

E.g. this is used in this complex diagram showing FrameNet nodes.

=for html
<img src="img/MS-Frame-complex.png">

=for text
See F<img/MS-Frame-complex.png>

=back

=head2 Labels

Nodes can have labels: C<puml:label, rdfs:label, skos:prefLabel>.

=over

=item *

If a node is inlined, its label is added as a comment. If several nodes are inlined at the same property, all their comments are also gathered together.

=item *

If a node is shown normally, its label is shown amongst the other node attributes.
As an exception, C<puml:label> is used to give a label (or comment) without any attribute.

=back


=head2 Arrow Customization

B<rdfpuml> allows you to customize arrows by using properties like C<puml:DIR-HEAD-LINE-COLOR-LEN>.
You can combine the different parts freely (each is optional) and even write them in different order.

=over

=item DIR

Arrow direction: C<left, right, up> or C<down> (default)

=item HEAD

Arrowhead (end): C<none> (use for symmetric properties), C<tri> (hollow triangle), C<star> (filled dot), C<o> (empty dot).
Unfortunately you cannot customize the arrowtail (beginning), it's always empty.

=item LINE

Line style: C<dotted, dashed, bold, hidden>.

C<dotted, dashed> are exclusive of each other; C<bold> can be used alone or with them.
C<hidden> can be used to adjust the layout by constraining node positions, and is exclusive of the other line attributes.

=item COLOR

Line color: name (e.g. C<red>) or hex-code (e.g. C<FF0000>)
To see the full list of color names supported by PlantUML, use this command and search for C<;color>

  java -jar plantuml.jar -language

For example, 4 of the arrows on this diagram are colored (1 green, 3 red):

=for html
<img src="img/colorArrow-ciq-cropped.png">

=for text
See F<img/colorArrow-ciq-cropped.png>

=item LEN

Length: a number of 1 or 2 digits. This applies only to vertical arrows (C<up,down>).
You can use this to adjust the layout and in some cases avoid the need for parasitic C<hidden> arrows.

See L<this example|http://www.plantuml.com/plantuml/uml/JOvB3iCW30NtFeKlm2B_NPMhq80A4YGH6DMvVLCtZM0tCvOUSoQTgCG0pXkBDkvqe2PA_bd8vjf6IsupbrfyMiBPbw1pHcw06rHcUw_gWST9BQgogo-qmDsLX3lW_XS5U-3Xpc86u54E_c84dgeJSPDC9FzofEft3zH9VZ7RrPGOFW00>
and its remake in rdfpuml below.


=for html
<img src="img/arrowLen.png">

=for text
See F<img/arrowLen.png>

=back

=head3 Arrow Per Edge

To customize the arrow of one relation connecting two nodes, use:

  <node1> puml:DIR-HEAD-LINE-COLOR <node2>

=head3 Arrow Per Property

To customize the arrow for all relations with the same property, use:

  <prop> puml:arrow puml:DIR-HEAD-LINE-COLOR.

E.g. on the diagram L</Inlines>, the following declaration was used to point all C<nif:oliaLink> arrows upward:

  nif:oliaLink puml:arrow puml:up.

=head2 Stereotypes and Colored Circles

L<Stereotype|https://en.wikipedia.org/wiki/Stereotype_(UML)> is UML lingo for "role".
In PlantUML these include a «guillemetted italic label» and colored circle.

  puml:stereotype "(LETTER,COLOR)LABEL"

where C<LETTER> is a single uppercase letter,
C<COLOR> is a color name or hex-code (see </COLOR>),
C<LABEL> is a label, and all the parts are optional.

You can set stereotype on an individual node or a whole class, e.g.
(referring to the previous diagram):

  <#char=32,34_annoSet> puml:stereotype "(F)Frame"
  fn:AnnotationSet      puml:stereotype "(F)Frame"

Here is an example that also sets stereotype labels:

  gvp:GuideTerm      puml:stereotype "(G,green) Concept".
  gvp:Concept        puml:stereotype "(C,lightblue) ThesaurusArray, OrderedCollection".
  iso:ThesaurusArray puml:stereotype "(A,red) ThesaurusArray, OrderedCollection".

=for html
<img src="img/GVP-ordered-collection-Stereotype.png">

=for text
See F<img/GVP-ordered-collection-Stereotype.png>

Here is a bigger example that also shows how arrow directions are handled.
It's a diagram for the L<Duraspace Portland Common Data Model|https://github.com/duraspace/pcdm/wiki> for digital library metadata (Fedora, Islandora, etc):
a remake of one of the L<Reference Diagrams|https://wiki.duraspace.org/display/FF/PCDM%2BMappings%2B-%2BReference%2BDiagrams%2Bfor%2BComment>.
(A proposal to make L<PCDM diagrams with rdfpuml|https://github.com/duraspace/pcdm/wiki/Diagrams-with-rdfpuml>
is tracked as L<duraspace/pcdm#46|https://github.com/duraspace/pcdm/issues/46>)

=for html
<img src="img/PCDM_Multi_Page_Text-circles.png">

=for text
See F<img/PCDM_Multi_Page_Text-circles.png>

=head2 Blank Nodes

Although the use of blank nodes is not recommended in semantic modeling, they are supported by B<rdfpuml>.
No special triples are needed for this.

E.g. below is a diagram of L<EXAMPLE 41: Complete Example|https://www.w3.org/TR/annotation-model/#h-complete-example>
from the L<Web Annotation Data Model|https://www.w3.org/TR/annotation-model/>.

As you can see, 10 nodes on the right side are blank nodes (have no URL).
The tiny one in the middle has no attributes whatsoever, only the L<rdf:first, rdf:next> outgoing links.
It should have had a type L<rdf:List>, this is an omission in the example.

=for html
<img src="img/OA-eg41.png">

=for text
See F<img/OA-eg41.png>

=head2 Limitations

Round brackets in labels eg "(1975)" are converted to square brackets, eg "[1975]".
PlantUML interprets round brackets as a function (method) and renders them below a line, so I had to implement this hack.

=head2 Prerequisites

L<GraphViz|http://www.graphviz.org/>

L<PlantUML|http://plantuml.com/download>, see in particular L<plantuml class diagrams|http://plantuml.com/class-diagram>.

Perl. Tested with version 5.22 on Windows (cygwin and Strawberry).

Perl modules: F<RDF::Trine>, F<RDF::Query>, F<Encode>, F<FindBin>, F<Carp::Always>, F<Slurp>.

F<RDF::Prefixes::Curie>. This is my own module located in F<../lib>, and B<rdfpuml> needs F<FindBin> to locate it.

=head2 Installation

Until B<rdfpuml> is published as a proper perl package, use the following procedure:

Install the prerequisites.

Add F<rdfpuml/bin> to your path.

Use F<rdfpuml/bin/rdfpuml.bat> to run it:

  perl -S rdfpuml.pl %1

See F<test/*/Makefile> for examples how to set up make.

=head1 SEE ALSO

B<rdf2rml>: a tool to generate R2RML transformations from RDF examples.

If you use B<rdfpuml> or B<rdf2rml>, please cite them as follows. See this presentation for numerous examples.

B<RDF by Example: rdfpuml for True RDF Diagrams, rdf2rml for R2RML Generation>.
Alexiev, V. In Semantic Web in Libraries 2016 (SWIB 16), Bonn, Germany, November 2016.
L<Presentation|http://rawgit2.com/VladimirAlexiev/my/master/pres/20161128-rdfpuml-rdf2rml/index.html>,
L<HTML|http://rawgit2.com/VladimirAlexiev/my/master/pres/20161128-rdfpuml-rdf2rml/index-full.html>,
L<PDF|http://rawgit2.com/VladimirAlexiev/my/master/pres/20161128-rdfpuml-rdf2rml/RDF_by_Example.pdf>,
L<Video|https://youtu.be/4WoYlaGF6DE>

See L<https://twitter.com/hashtag/rdfpuml> for news, screenshots and announcements.

=head1 AUTHOR

Vladimir Alexiev, Ontotext Corp

Last update: 2018-11-14

=cut

# https://share.getty.edu/confluence/display/ITSLODV/rdfpuml
